### ISSUE TITLE
Issues with Podman

### ISSUE THREAD

**Issue by hiulit** [godotengine/buildroot#2]
Everything works fine until I get this message:

![Screenshot from 2021-06-04 16-53-18](https://user-images.githubusercontent.com/481475/121046626-54771e00-c7b6-11eb-98c9-48e04d578e3e.png)

If I select the first option, I get this error:
![Screenshot from 2021-06-04 16-53-34](https://user-images.githubusercontent.com/481475/121046875-635dd080-c7b6-11eb-9df1-1646fbeec5ed.png)

If I select the second option, I get this error:
![Screenshot from 2021-06-04 16-53-48](https://user-images.githubusercontent.com/481475/121046893-65279400-c7b6-11eb-8c62-6c79243bf43b.png)

I'm stuck here :)

**Comment by akien-mga** [comment]
Fixed by c9c4c6ce37d0efd8f264ce51287e5d02227e6d30.
