### ISSUE TITLE
dbus pkgconfig file doesn't properly point to arch-dependent include path

### ISSUE THREAD

**Issue by akien-mga** [godotengine/buildroot#6]
SDK version: 2021-02-11 on Linux host

Godot's `master` branch now has a dependency on dbus-1.0, and the `dbus-1.0/dbus.h` main header includes an internal, architecture dependent header which is therefore shipping in an archful path (`/usr/lib64/dbus-1.0/include/dbus/dbus-arch-deps.h`).

But the pkgconfig file in the buildroot doesn't seem to properly point to this path in the `Cflags`, so despite our call to `pkg-config dbus-1.0 --libs --cflags` in the Godot build scripts, it can't find the file:
```
/root/x86_64-godot-linux-gnu_sdk-buildroot/x86_64-godot-linux-gnu/sysroot/usr/include/dbus-1.0/dbus/dbus.h:29:10: fatal error: dbus/dbus-arch-deps.h: No such file or directory
   29 | #include <dbus/dbus-arch-deps.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
```

The file is at `x86_64-godot-linux-gnu_sdk-buildroot/x86_64-godot-linux-gnu/sysroot/usr/lib64/dbus-1.0/include/dbus/dbus.h` (similar path on my Mageia host OS, so that's expected from upstream).

Here's the pkgconfig file in the buildroot:
```
# cat x86_64-godot-linux-gnu_sdk-buildroot/x86_64-godot-linux-gnu/sysroot/usr/lib/pkgconfig/dbus-1.pc 
original_prefix=/usr
prefix=${original_prefix}
exec_prefix=/usr
bindir=${exec_prefix}/bin
libdir=${exec_prefix}/lib
includedir=${prefix}/include
system_bus_default_address=unix:path=/run/dbus/system_bus_socket
datarootdir=${prefix}/share
datadir=${datarootdir}
sysconfdir=/etc
session_bus_services_dir=${datadir}/dbus-1/services
system_bus_services_dir=${datadir}/dbus-1/system-services
interfaces_dir=${datadir}/dbus-1/interfaces
daemondir=${bindir}

Name: dbus
Description: Free desktop message bus
Version: 1.12.20
Libs: -L${libdir} -ldbus-1
Libs.private: -lpthread    -L/root/x86_64-godot-linux-gnu_sdk-buildroot/bin/../x86_64-godot-linux-gnu/sysroot/usr/lib -lsystemd 
Cflags: -I${includedir}/dbus-1.0 -I${libdir}/dbus-1.0/include
```

So it has `-I${libdir}/dbus-1.0/include` in the `Cflags` as it should, but `libdir` is wrong. Note how the pkgconfig files are under `/usr/lib` while the libs are under `/usr/lib64` in the sysroot, while on a typical Fedora/Mageia setup both should be under `/usr/lib64`.

**Comment by Zylann** [comment]
Still happening, I tried using the buildroot but hit the same error.

**Comment by akien-mga** [comment]
You can patch it as a workaround: https://github.com/godotengine/godot-build-scripts/blob/09b9dcf96953e93743e694766650709c66c83d65/build-linux/build.sh#L17-L18

**Comment by akien-mga** [comment]
Fixed in https://github.com/godotengine/buildroot/tree/2023.08.x
