### ISSUE TITLE
Sync with upstream buildroot changes

### ISSUE THREAD

**Issue by akien-mga** [godotengine/buildroot#8]
We currently have a soft fork of buildroot's [2020.11.x](https://github.com/buildroot/buildroot/tree/2020.11.x) branch. The latest upstream is [2022.11.x](https://github.com/buildroot/buildroot/tree/2022.11.x).

There are two things we could consider doing:
- Rebase our 2020.11.x branch on upstream's, to get their latest fixes in that series.
- Update straight to 2022.11.x (or whichever is the latest stable branch when doing this work) to get all the latest goodies.
  * This is a bit harder, but given that it's 2 years worth of changes it might be worth it. We need to make sure in that process that we can keep a good overview of where the Godot-specific changes are made so that future rebases / upgrades are easy.

**Comment by akien-mga** [comment]
> Update straight to 2022.08.x (or whichever is the latest stable branch when doing this work) to get all the latest goodies. 

@Faless had rebased on 2022.02.x a few months ago in https://github.com/Faless/buildroot/commits/2022.02.x-fales, so we could start from there.

**Comment by hpvb** [comment]
Done!
